### ISSUE TITLE
2.us.pool.ntp.org

### ISSUE THREAD

**Issue by StevenBlack** [CapedCrusader42/IfunnyAdBlocker#3]
Hi @CapedCrusader42.

Are you aware your list blocks `2.us.pool.ntp.org`?

I wouldn't do that 😄 

Cheers!

**Comment by NoahCrust** [comment]
Why is it not good to block?

**Comment by doomdoxrulz** [comment]
Its a time server used for syncing time to devices

**Comment by CapedCrusader42** [comment]
I do now, thanks!
