### ISSUE TITLE
Ads appearing again

### ISSUE THREAD

**Issue by savedude** [CapedCrusader42/IfunnyAdBlocker#6]
A whole bunch of ads in comments and regular swiping are appearing again after using these for a long time.

**Comment by Kasra-G** [comment]
Block the following:
`cdn.liftoff.io`
`aktrack.pubmatic.com`

**Comment by CosmicFireBlast** [comment]
> Block the following: `cdn.liftoff.io` `aktrack.pubmatic.com` `impression-asia.liftoff.io` `s.update.rose.pubmatic.com` `adexp.liftoff.io`
> 
> Blocking these blocked most if not all the ads for me

I was getting ads in the comments even after adding the full updated list. After I added these five that you suggested, the ads in the comments have stopped. Thank you!
